- ansible.builtin.import_role:
    name: compose_hull
    tasks_from: prepare
  vars:
    service_defaults:
      directory: "{{ docker_dir }}/wordpress"
      subdirs: ["maria", "wordpress"]
      name: wordpress
      port: 80
      traefik: true
      external: true
      watchtower: true
      autoheal: true
      skip_network_definition: false

- name: "Change ownership to maria:maria inside the container (UID 999, GID 999)"
  ansible.builtin.file:
    path: '{{ service_cfg.directory }}/maria'
    owner: 999
    group: 999

- name: "Copy {{ service_cfg.name }} nginx.conf"
  template:
    src: nginx.conf.j2
    dest: '{{ service_cfg.directory }}/nginx.conf'
    owner: '{{ admin.name }}'
    group: 'docker'
  tags: [ always ]

- name: "Copy {{ service_cfg.name }} uploads.ini"
  ansible.builtin.copy:
    src: uploads.ini
    dest: '{{ service_cfg.directory }}/uploads.ini'
  tags: [ always ]

- name: "Copy {{ service_cfg.name }} utf8fix.cnf"
  ansible.builtin.copy:
    src: utf8fix.cnf
    dest: '{{ service_cfg.directory }}/utf8fix.cnf'
  tags: [ always ]

- ansible.builtin.import_role:
    name: compose_hull
    tasks_from: deploy_docker